name: deploy to azure app services
on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: deploy to azure app services 
      uses: actions/checkout@v3

    - name: Setup Node 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: 'npm install, build, and test'
      run: |
        npm i
        npm start

    - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: projectankur
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
